In [5]:
import numpy as np

In [6]:
array_1 = np.array([0, 2,4,6,8])
print(array_1)

[0 2 4 6 8]


In [7]:
array_2 = np.array([[1,3,5,7,9],[0,2,4,6,8]])
print(array_2)

[[1 3 5 7 9]
 [0 2 4 6 8]]


In [8]:
array_n = np.array([[0], [1,2], [3,4,5],[6,7,8,9]])
print(array_n)

[list([0]) list([1, 2]) list([3, 4, 5]) list([6, 7, 8, 9])]


<ipython-input-8-a20ec94e807e>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  array_n = np.array([[0], [1,2], [3,4,5],[6,7,8,9]])


In [9]:
range_a = np.arange(10)
print(range_a)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
range_b = np.arange(8, 23)
print(range_b)

[ 8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


In [15]:
range_c = np.arange(1, 2, .02)
print(range_c)

[1.   1.02 1.04 1.06 1.08 1.1  1.12 1.14 1.16 1.18 1.2  1.22 1.24 1.26
 1.28 1.3  1.32 1.34 1.36 1.38 1.4  1.42 1.44 1.46 1.48 1.5  1.52 1.54
 1.56 1.58 1.6  1.62 1.64 1.66 1.68 1.7  1.72 1.74 1.76 1.78 1.8  1.82
 1.84 1.86 1.88 1.9  1.92 1.94 1.96 1.98]


In [12]:
range_zero = np.zeros((3,3))
print(range_zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
range_one = np.ones((2, 2))
print(range_one)

[[1. 1.]
 [1. 1.]]


In [17]:
range_random = np.random.random((4,4))
print(range_random)

[[0.09879488 0.90050093 0.72642869 0.97814022]
 [0.85587105 0.56936544 0.82891272 0.51457453]
 [0.41658817 0.52402307 0.94718157 0.91726878]
 [0.63306028 0.1893097  0.79848665 0.39684218]]


In [18]:
print("Dimensões:")
print(range_a.ndim)
print(range_b.ndim)
print(range_c.ndim)
print(range_zero.ndim)
print(range_one.ndim)
print(range_random.ndim)

Dimensões:
1
1
1
2
2
2


In [20]:
print("Forma:")
print(range_a.shape)
print(range_b.shape)
print(range_c.shape)
print(range_zero.shape)
print(range_one.shape)
print(range_random.shape)

Forma:
(10,)
(15,)
(50,)
(3, 3)
(2, 2)
(4, 4)


In [21]:
print("Tipo:")
print(range_a.dtype)
print(range_b.dtype)
print(range_c.dtype)
print(range_zero.dtype)
print(range_one.dtype)
print(range_random.dtype)

Tipo:
int32
int32
float64
float64
float64
float64


In [22]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array)
print(array[3])
print(array[3:7])

[1 2 3 4 5 6 7 8 9]
4
[4 5 6 7]


In [40]:
array_n = np.array([[1, 2, 3], [10, 20, 30], [11, 22, 33], [100, 200, 300]])

print(array_n[0,1])
print(array_n[1,1])
print(array_n[2,1])
print(array_n[3,1])
print('--')
print(array_n[3])
print(array_n[1:3])
print('--')
print(array_n[2, :])
print(array_n[:,2])

2
20
22
200
--
[100 200 300]
[[10 20 30]
 [11 22 33]]
--
[11 22 33]
[  3  30  33 300]


In [50]:
array_n = np.array([[1, 2, 3], [10, 20, 30], [11, 22, 33], [100, 200, 300]])
print(array_n)
print("-")
print(array_n.reshape(3,4))
print("-")
print(array_n.reshape(2,6))
print("-")
print(array_n.reshape(1,12))

[[  1   2   3]
 [ 10  20  30]
 [ 11  22  33]
 [100 200 300]]
-
[[  1   2   3  10]
 [ 20  30  11  22]
 [ 33 100 200 300]]
-
[[  1   2   3  10  20  30]
 [ 11  22  33 100 200 300]]
-
[[  1   2   3  10  20  30  11  22  33 100 200 300]]


In [54]:
array_a = np.array([9,7,5,3,1])
array_b = np.array([8,6,4,2,0])

array_c = array_a - array_b
print(array_c)

array_d = array_b + array_c
print(array_d)


[1 1 1 1 1]
[9 7 5 3 1]
